init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE

stack:
  - jdk 7
  - jdk 8
  - jdk 9
  - jdk 10
  - jdk 11
  - jdk 12
  - jdk 13
    
test_script:
- sh: env
- sh: echo $PATH | tr ':' '\n'
- sh: java -version
- sh: javac -version
- sh: |    
    declare -A VERSIONS
    VERSIONS["7"]="1.7.0"
    VERSIONS["8"]="1.8.0"
    VERSIONS["9"]="9.0.4"
    VERSIONS["10"]="(javac|build) 10"
    VERSIONS["11"]="(javac|build) 11"
    VERSIONS["12"]="(javac|build) 12"
    VERSIONS["13"]="(javac|build) 13"
    if [[ $(java -version 2>&1) =~ ${VERSIONS[$APPVEYOR_STACK_JDK]} ]] && [[ $(javac -version 2>&1) =~ ${VERSIONS[$APPVEYOR_STACK_JDK]} ]]; then
        echo "Version is Correct"
    else
        echo "[ERROR] Version of JDK is incorrect!"
        return 1
    fi

build: off
