init:
- appveyor version
 
stack:
  - jdk 7
  - jdk 8
  - jdk 9
  - jdk 10

test_script:
- sh: env
- sh: echo $PATH|tr ':' ''\n'
- sh: |    
    declare -A VERSIONS
    VERSIONS["7"]="1.7.0"
    VERSIONS["8"]="1.8.0"
    VERSIONS["9"]="9-internal"
    VERSIONS["10"]="(javac|build) 10"
    java -version
    javac -version
    if [[ $(java -version 2>&1) =~ ${VERSIONS[$APPVEYOR_STACK_JDK]} ]] && [[ $(javac -version 2>&1) =~ ${VERSIONS[$APPVEYOR_STACK_JDK]} ]]; then
        echo "Version is Correct"
    else
        echo "[ERROR] Version of JDK is incorrect!" 1>&2;
        exit 2;
    fi

build: off
